Improvement on scripts
end-4/dots-hyprland pull request #170
Opened 2024-01-03 13:52 UTC by clsty

See the titles of commits.

2024-01-03 14:13 UTC, clsty commented
Notice that now `./install.sh -f` do things automatically without confirm.
> That's pretty handy for me when I'm debugging. i.e. After I edited the repo, I use the script with `-f` and it finish in seconds.

2024-01-04 01:17 UTC, clsty commented
About "Read dependencies from a file":
Now each line will be asked during installation.

Packages in `dependencies.txt` can be splited by spaces or returns.
But comments in this file is currently not supported.

2024-01-04 14:14 UTC, clsty commented
@end-4 Any comment on this PR is welcomed. 
Please let me know if there's anything not good enough on this PR.

2024-01-04 16:50 UTC, end-4 requested changes

2024-01-04 16:50 UTC, end-4 commented on install.sh
> +      echo "  s = Skip this command; NOT recommended (may break functions needed by the dot files!)"
"dotfiles" not "dot files"

2024-01-04 16:50 UTC, end-4 commented on install.sh
> +printf "ALREADY BACKUPED\n"
- "backed up" not "backuped"
- Also I don't think it's necessary to have this on so many lines. A non-white color that stands out should be enough.
- So I'd rather have something like this:
```
Please CONFIRM that you HAVE ALREADY BACKED UP $HOME/.config and $HOME/.local folders
Enter "YES" (in capitals, without quotes) to continue: 
```

2024-01-04 16:51 UTC, end-4 commented
finally have some time to review this, sorry for the slow response

2024-01-04 22:48 UTC, clsty commented
Thanks for reviewing. Is that better now?

2024-01-05 00:21 UTC, end-4 approved these changes
alright

2024-01-05 00:22 UTC, merged