update dock
end-4/dots-hyprland pull request #422
Opened 2024-04-17 19:26 UTC by casglistro

I'm used to dock so I updated the `dock` in the `modules`, I don't know why it's not being used.
![图片](https://github.com/end-4/dots-hyprland/assets/95210542/54b9d0d0-8e43-4d0e-85a9-f13057fbef93)
It generally continues the design from the dock, but it is always placed at the top level and only exists on one monitor at most. When focusing on another monitor, the dock will move to that monitor. It also hides itself when `onHoverLost` is triggered, and there is a button to hold the dock in place.
For the missing icons, I do a recursive search in the system's icon path, preprocessing the path of each image under the path and storing it in an array at ags startup. When an icon is needed use `Levenshtein Distance` to find the closest string according to the class of the window. In my tests it seems that a lot of all icons can be corresponded to. However, there are requirements for the search path: if there are too many images there is an expensive performance hit, if there are too few images there may be missing icons, so I chose `tela-icon-theme`.
If you have suggestions or complaints please let me know.

2024-04-17 22:55 UTC, clsty commented
> I'm used to dock so I updated the dock in the modules, I don't know why it's not being used.

I don't know either, but there are some people who don't like dock, such as me.
I suggest you to make an option to enabled/disabled the dock in `user_options.js`.

2024-04-18 00:26 UTC, end-4 commented
I disabled dock since I haven't managed to get it work correctly and don't really care (I mean, we use a *tiling* window manager). But having it optional is the way now that there's a config file.

2024-04-18 00:32 UTC, end-4 requested changes

2024-04-18 00:32 UTC, end-4 commented on .config/ags/modules/dock/dock.js
> +const icon_files = getAllFiles("/usr/share/icons/Tela-nord-dark/scalable/apps")
don't hard code it

2024-04-18 00:32 UTC, end-4 commented on .config/ags/modules/dock/dock.js
> +            css: 'min-height: 20px;',
20px would be too much and might block apps. can you add a config option and have it default to 5? (since that's the hyprland outer gap value)

2024-04-18 08:57 UTC, end-4 commented on .config/ags/modules/.configuration/user_options.js
> +        'city': "Chengdu",
ughh don't

2024-04-18 08:57 UTC, end-4 commented on .config/ags/modules/.configuration/user_options.js
> +        'iconSearchPaths': [''],
let's move this to an 'icon' category since i wanna have this icon guessing for overview too

2024-04-18 09:02 UTC, casglistro commented on .config/ags/modules/.configuration/user_options.js
> +        'city': "Chengdu",
ohh i forget it :(

2024-04-18 11:39 UTC, end-4 commented
i removed the active workspace trigger since the dock showing up every time switching workspace is kinda weird

2024-04-18 12:09 UTC, end-4 commented
alrighty, thanks for your work!

2024-04-18 12:09 UTC, merged