Adding randomwall and ollama
end-4/dots-hyprland pull request #532
Opened 2024-05-24 10:40 UTC by Soliprem

- Changes to the switchwall script so that it can also take a positional $1 argument in the form of a wallpaper path
- Added randomwall script
- Added Ollama (with default model llama3:instruct. This could be changed in favour of a smaller model. Requires ollama to be installed and running on the system)
- Tested on my system with no issues

2024-05-24 10:45 UTC, Soliprem commented
Not sure why the first commit reports a change to the hyprlock config file. Must have accidentally opened it and the linter might have added a space. No functional change, though

2024-05-24 11:27 UTC, end-4 requested changes

2024-05-24 11:27 UTC, end-4 commented on .config/ags/assets/icons/ollama.png
use svg
force push so the png doesn't take up space

2024-05-24 11:27 UTC, end-4 commented on .config/ags/scripts/color_generation/randomwall.sh
> +$CONFIG_DIR/scripts/color_generation/switchwall.sh $(fd . ~/Images/wallpapers/ -e .png -e .jpg -e .svg | xargs shuf -n1 -e)
~/Pictures not ~/Images

2024-05-24 11:27 UTC, end-4 commented on .config/ags/scripts/color_generation/switchwall.sh
> +	swww img "$imgpath" --transition-step 1 --transition-fps 120 \
--transition-step 100 pls

2024-05-24 11:31 UTC, end-4 commented on .config/ags/scripts/color_generation/randomwall.sh
> +$CONFIG_DIR/scripts/color_generation/switchwall.sh $(fd . ~/Images/wallpapers/ -e .png -e .jpg -e .svg | xargs shuf -n1 -e)
fixed

2024-05-24 11:31 UTC, end-4 commented on .config/ags/scripts/color_generation/switchwall.sh
> +	swww img "$imgpath" --transition-step 1 --transition-fps 120 \
fixed

2024-05-24 11:38 UTC, end-4 commented on .config/ags/assets/icons/ollama.png
done

2024-05-24 11:46 UTC, end-4 commented on .config/ags/assets/icons/ollama.png
force push removed
added svg in bf62babb29a027ba33ca9f15cb48e86ef17085f2

2024-05-24 11:50 UTC, merged

2024-05-24 11:57 UTC, Soliprem commented
Thanks for the fixes! Those are preferences from my personal config and forgot I changed them

2024-05-25 01:33 UTC, end-4 commented
somehow this pr doubled the commit count lol
guess i shouldn't use git-filter-repo on a pr next time